#!/usr/bin/env -S node --experimental-strip-types --no-warnings
/**
 * gen-sense-images.mts — generate icon/still-life images for the 6
 * wrażenia (sektory) and 12 tendencje, inspired by the canonical
 * Vinokompas wheel (citrus for Świeże, leather/oak for Szorstkie, etc.).
 *
 * Style: moody dark still-life on slate, matching the dish/wine photos —
 * a tight composition of the key associations for each impression. These
 * are the "obrazki" the client asked for under the compass / in the side
 * panel at stages 2 and 3.
 *
 * Output:
 *   public/senses/<sektorId>.png         (6)
 *   public/senses/<tendencjaId>.png      (12, id has a dot → use slug)
 *   src/data/sense-images.ts             (SENSE_IMAGE_MAP)
 *
 * Cost: ~$0.04 × 18 = ~$0.72.
 */

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
loadEnv({ path: ".env" });

import OpenAI from "openai";
import fs from "node:fs/promises";
import path from "node:path";
// @ts-expect-error — Node 23 strip-types requires explicit .ts ext.
import { COMPASS_SECTORS } from "../src/data/wine-compass-kb.ts";

const apiKey = process.env.OPENAI_API_KEY;
if (!apiKey) {
  console.error("OPENAI_API_KEY missing");
  process.exit(1);
}
const openai = new OpenAI({ apiKey });
const FORCE = process.env.FORCE === "1";
const PUBLIC_DIR = path.resolve(process.cwd(), "public", "senses");

const slug = (id: string) => id.replace(/\./g, "-");

const promptFor = (title: string, associations: string): string =>
  [
    "Moody editorial still-life, top-down, on a dark slate / charcoal surface.",
    `Theme: "${title}" — a tight artful arrangement of: ${associations}.`,
    "Single cohesive composition, warm low-key lighting from upper left,",
    "deep shadows, a faint gold rim-light. Wine-bar magazine aesthetic.",
    "No text, no labels, no people, no glassware, no watermark.",
    "Photorealistic, sharp focus, professional 4K, gentle film grain.",
  ].join(" ");

async function fileExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function genOne(
  id: string,
  title: string,
  associations: string,
): Promise<string | null> {
  await fs.mkdir(PUBLIC_DIR, { recursive: true });
  const file = `${slug(id)}.png`;
  const outPath = path.join(PUBLIC_DIR, file);
  const rel = `/senses/${file}`;

  if (!FORCE && (await fileExists(outPath))) {
    console.log(`SKIP ${id} (exists)`);
    return rel;
  }

  console.log(`GEN  ${id} :: ${title}`);
  try {
    // gpt-image-1 — current OpenAI image model (dall-e-3 was retired from
    // this account). Returns base64 (no url), quality low|medium|high.
    const r = await openai.images.generate({
      model: "gpt-image-1",
      prompt: promptFor(title, associations),
      size: "1024x1024",
      quality: "medium",
      n: 1,
    });
    const b64 = r.data?.[0]?.b64_json;
    if (!b64) {
      console.error("  → no image data");
      return null;
    }
    await fs.writeFile(outPath, Buffer.from(b64, "base64"));
    console.log(`  → saved ${rel}`);
    return rel;
  } catch (e) {
    console.error("  → API error", e instanceof Error ? e.message : e);
    return null;
  }
}

async function writeMap(map: Record<string, string>) {
  const lines = [
    "/**",
    " * sense-images.ts — generated by scripts/gen-sense-images.mts.",
    " * Maps sektor id + tendencja id to their still-life image URL.",
    " * Do NOT hand-edit; re-run the script.",
    " */",
    "",
    "export const SENSE_IMAGE_MAP: Record<string, string> = {",
    ...Object.keys(map).sort().map((id) => `  "${id}": "${map[id]}",`),
    "};",
    "",
    "export const getSenseImageById = (id: string): string | null =>",
    "  SENSE_IMAGE_MAP[id] ?? null;",
    "",
  ];
  const out = path.resolve(process.cwd(), "src", "data", "sense-images.ts");
  await fs.writeFile(out, lines.join("\n"), "utf8");
  console.log(`\nWrote ${out} (${Object.keys(map).length} entries)`);
}

async function main() {
  const map: Record<string, string> = {};
  let ok = 0;
  let failed = 0;

  for (const s of COMPASS_SECTORS) {
    // Sektor image — blend of both tendencje associations.
    const assoc = s.tendencje.map((t: { associations_pl: string }) => t.associations_pl).join("; ");
    const res = await genOne(s.id, s.name_pl, assoc);
    if (res) {
      map[s.id] = res;
      ok++;
    } else failed++;
    await new Promise((r) => setTimeout(r, 400));

    // Each tendencja image.
    for (const t of s.tendencje) {
      const r2 = await genOne(t.id, t.name_pl, t.associations_pl);
      if (r2) {
        map[t.id] = r2;
        ok++;
      } else failed++;
      await new Promise((r) => setTimeout(r, 400));
    }
  }

  await writeMap(map);
  console.log(`\n=== Done ===\n  ok: ${ok}\n  failed: ${failed}`);
  if (failed > 0) process.exit(2);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
