#!/usr/bin/env -S npx tsx
/**
 * gen-dish-images.mts — generate 50 dish photos via DALL·E 3.
 *
 * Reads seedRestaurants, for each dish without an existing file at
 * public/dishes/<slug>/<dish-id>.png it asks DALL·E 3 for a single
 * editorial restaurant photo, downloads the result and saves it.
 *
 * Idempotent: skips dishes whose image already exists. Run multiple
 * times safely; only missing files get generated.
 *
 * Cost: ~$0.04 per image × ~50 dishes = ~$2.
 *
 * Usage:
 *   tsx scripts/gen-dish-images.mts            # all restaurants
 *   tsx scripts/gen-dish-images.mts atelier-amaro   # single restaurant
 *   FORCE=1 tsx scripts/gen-dish-images.mts    # regenerate even if exists
 *
 * After running, also writes src/data/dish-images.ts — a tiny static
 * map { dishId → url } that the rendering layer reads as fallback for
 * dishes whose seed entry has no `image` field.
 */

// Load .env.local explicitly — Next.js convention; default `dotenv/config`
// only reads `.env`. Without this OPENAI_API_KEY is undefined.
import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
loadEnv({ path: ".env" });

import OpenAI from "openai";
import fs from "node:fs/promises";
import path from "node:path";
// @ts-expect-error — Node 23's --experimental-strip-types resolver requires
// the explicit `.ts` extension; tsconfig forbids it. The script runs OK at
// runtime via `node --experimental-strip-types` (or `tsx` once env aligned).
import { seedRestaurants } from "../src/data/seed-restaurants.ts";

// Inline t() so we don't pull lib/localized.ts (it imports from @/ aliases
// that tsx can't resolve without the path-mapping plugin).
const t = (v: { en: string; pl: string }, locale: "en" | "pl"): string =>
  (v?.[locale] ?? v?.en ?? v?.pl ?? "").trim();

const apiKey = process.env.OPENAI_API_KEY;
if (!apiKey) {
  console.error("OPENAI_API_KEY missing — set it in .env.local");
  process.exit(1);
}

const openai = new OpenAI({ apiKey });
const FORCE = process.env.FORCE === "1";
const ONLY_SLUG = process.argv[2];

const PUBLIC_DIR = path.resolve(process.cwd(), "public", "dishes");

// Cuisine-aware prompt template. Keeps photos consistent (dark wood,
// natural light, top-down) so the catalogue feels like one magazine
// shot by the same photographer, not a Pinterest dump.
const promptFor = (
  cuisine: string,
  dishNameEn: string,
  dishDescEn: string,
  category: string,
): string =>
  [
    "Editorial restaurant food photography, single hero plating.",
    `Dish: "${dishNameEn}". Cuisine: ${cuisine}. Category: ${category}.`,
    `Composition notes: ${dishDescEn}`,
    "Plated on rustic dark wood or matte ceramic, natural diffused window light from the upper left.",
    "30-degree top-down angle, shallow depth of field, the dish fills 70% of the frame.",
    "Magazine wine-bar aesthetic, warm tones, no people, no text, no watermark, no logo.",
    "Photorealistic, sharp focus, professional 4K, gentle film grain.",
  ].join(" ");

async function fileExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function generateOne(
  restaurantSlug: string,
  cuisine: string,
  dishId: string,
  dishNameEn: string,
  dishDescEn: string,
  category: string,
): Promise<{ outPath: string; relPath: string } | null> {
  const dir = path.join(PUBLIC_DIR, restaurantSlug);
  await fs.mkdir(dir, { recursive: true });

  const outPath = path.join(dir, `${dishId}.png`);
  const relPath = `/dishes/${restaurantSlug}/${dishId}.png`;

  if (!FORCE && (await fileExists(outPath))) {
    console.log(`SKIP ${restaurantSlug}/${dishId} (exists)`);
    return { outPath, relPath };
  }

  const prompt = promptFor(cuisine, dishNameEn, dishDescEn, category);
  console.log(`GEN  ${restaurantSlug}/${dishId} :: ${dishNameEn}`);

  try {
    const r = await openai.images.generate({
      model: "dall-e-3",
      prompt,
      size: "1024x1024",
      quality: "standard",
      n: 1,
    });
    const url = r.data?.[0]?.url;
    if (!url) {
      console.error(`  → no URL returned`);
      return null;
    }
    const img = await fetch(url);
    if (!img.ok) {
      console.error(`  → download failed (${img.status})`);
      return null;
    }
    const buf = Buffer.from(await img.arrayBuffer());
    await fs.writeFile(outPath, buf);
    console.log(`  → saved ${relPath} (${(buf.length / 1024).toFixed(0)}KB)`);
    return { outPath, relPath };
  } catch (e) {
    console.error(`  → API error:`, e instanceof Error ? e.message : e);
    return null;
  }
}

async function writeImageMap(map: Record<string, string>): Promise<void> {
  const lines = [
    "/**",
    " * dish-images.ts — generated by scripts/gen-dish-images.mts.",
    " * Maps every dish id to its public-served photo URL. Consumed by",
    " * the rendering layer when the dish's seed entry has no `image`.",
    " * Do NOT hand-edit; re-run the script.",
    " */",
    "",
    "export const DISH_IMAGE_MAP: Record<string, string> = {",
    ...Object.keys(map)
      .sort()
      .map((id) => `  "${id}": "${map[id]}",`),
    "};",
    "",
    "export const getDishImageById = (id: string): string | null =>",
    "  DISH_IMAGE_MAP[id] ?? null;",
    "",
  ];
  const outPath = path.resolve(process.cwd(), "src", "data", "dish-images.ts");
  await fs.writeFile(outPath, lines.join("\n"), "utf8");
  console.log(`\nWrote ${outPath} (${Object.keys(map).length} entries)`);
}

async function main() {
  const restaurants = ONLY_SLUG
    ? seedRestaurants.filter((r) => r.slug === ONLY_SLUG)
    : seedRestaurants;
  if (restaurants.length === 0) {
    console.error(`No restaurants matched slug "${ONLY_SLUG}"`);
    process.exit(1);
  }

  let total = 0;
  let ok = 0;
  let failed = 0;
  const map: Record<string, string> = {};

  for (const r of restaurants) {
    console.log(`\n=== ${r.slug} (${r.cuisine}) — ${r.dishes.length} dishes ===`);
    for (const dish of r.dishes) {
      total++;
      const res = await generateOne(
        r.slug,
        r.cuisine,
        dish.id,
        t(dish.name, "en"),
        t(dish.description, "en"),
        dish.category,
      );
      if (res) {
        ok++;
        map[dish.id] = res.relPath;
      } else {
        failed++;
      }
      // Small delay to avoid hammering the API
      await new Promise((res) => setTimeout(res, 400));
    }
  }

  await writeImageMap(map);

  console.log(`\n=== Done ===`);
  console.log(`  total : ${total}`);
  console.log(`  ok    : ${ok}`);
  console.log(`  failed: ${failed}`);
  if (failed > 0) process.exit(2);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
