#!/usr/bin/env -S node --experimental-strip-types --no-warnings
/**
 * gen-wine-images.mts — generate 40 wine bottle photos via DALL·E 3.
 *
 * Wines tend to ship with brand-recognisable Wikimedia photos (handled
 * already in restaurant-pairing-adapter.ts for Trimbach/Chablis/Banfi/
 * Veuve/Penfolds). For the rest of the cellar we fall back to category
 * Unsplash bottle shots — fine but generic. This script generates a
 * unique shot per wine using DALL·E 3, with the LABEL TEXT explicitly
 * NOT requested (DALL·E renders text poorly; cleaner to leave the
 * label blank/blurred).
 *
 * Cost: ~$0.04 × 40 wines = ~$1.60.
 *
 * Output: public/wines/<restaurant-slug>/<wine-id>.png + appends to
 * src/data/wine-images.ts (parallel to dish-images.ts).
 */

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });
loadEnv({ path: ".env" });

import OpenAI from "openai";
import fs from "node:fs/promises";
import path from "node:path";
// @ts-expect-error — Node 23 strip-types resolver requires .ts ext.
import { seedRestaurants } from "../src/data/seed-restaurants.ts";

const apiKey = process.env.OPENAI_API_KEY;
if (!apiKey) {
  console.error("OPENAI_API_KEY missing — set it in .env.local");
  process.exit(1);
}
const openai = new OpenAI({ apiKey });
const FORCE = process.env.FORCE === "1";
const ONLY_SLUG = process.argv[2];
const PUBLIC_DIR = path.resolve(process.cwd(), "public", "wines");

const t = (v: { en: string; pl: string }, locale: "en" | "pl"): string =>
  (v?.[locale] ?? v?.en ?? v?.pl ?? "").trim();

// Wine bottle prompt — emphasise the bottle silhouette, no readable text.
// "blank label" / "label blurred" hints to keep DALL·E from inventing
// gibberish vintage years on the foil.
const promptFor = (
  wineName: string,
  region: string,
  grape: string,
  style: string,
  notes: string,
): string =>
  [
    "Editorial wine photography: a single hero bottle on a dark wooden table.",
    `Wine: ${style} ${grape} from ${region}. Tasting notes: ${notes}`,
    "Bottle silhouette is the hero — appropriate shape for the style",
    "(burgundy bottle for pinot/chardonnay, bordeaux for cabernet/merlot,",
    "hock for riesling, champagne flute-shoulder for sparkling).",
    "Label is intentionally blank/blurred (no readable text), foil capsule visible.",
    "Natural diffused window light from the upper left, low-key contrast,",
    "the bottle fills 80% of the frame vertically, shallow depth of field.",
    "Magazine wine-cellar aesthetic, warm tones, no people, no logo,",
    "no readable text whatsoever, no watermark.",
    "Photorealistic, sharp focus, professional 4K, gentle film grain.",
  ].join(" ");

async function fileExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function generateOne(
  restaurantSlug: string,
  wineId: string,
  wineNameEn: string,
  region: string,
  grape: string,
  style: string,
  notesEn: string,
): Promise<{ outPath: string; relPath: string } | null> {
  const dir = path.join(PUBLIC_DIR, restaurantSlug);
  await fs.mkdir(dir, { recursive: true });
  const outPath = path.join(dir, `${wineId}.png`);
  const relPath = `/wines/${restaurantSlug}/${wineId}.png`;

  if (!FORCE && (await fileExists(outPath))) {
    console.log(`SKIP ${restaurantSlug}/${wineId} (exists)`);
    return { outPath, relPath };
  }

  const prompt = promptFor(wineNameEn, region, grape, style, notesEn);
  console.log(`GEN  ${restaurantSlug}/${wineId} :: ${wineNameEn}`);

  try {
    const r = await openai.images.generate({
      model: "dall-e-3",
      prompt,
      size: "1024x1024",
      quality: "standard",
      n: 1,
    });
    const url = r.data?.[0]?.url;
    if (!url) {
      console.error(`  → no URL returned`);
      return null;
    }
    const img = await fetch(url);
    if (!img.ok) {
      console.error(`  → download failed (${img.status})`);
      return null;
    }
    const buf = Buffer.from(await img.arrayBuffer());
    await fs.writeFile(outPath, buf);
    console.log(`  → saved ${relPath} (${(buf.length / 1024).toFixed(0)}KB)`);
    return { outPath, relPath };
  } catch (e) {
    console.error(`  → API error:`, e instanceof Error ? e.message : e);
    return null;
  }
}

async function writeImageMap(map: Record<string, string>): Promise<void> {
  const lines = [
    "/**",
    " * wine-images.ts — generated by scripts/gen-wine-images.mts.",
    " * Maps every wine id to its public-served bottle photo URL.",
    " * Do NOT hand-edit; re-run the script.",
    " */",
    "",
    "export const WINE_IMAGE_MAP: Record<string, string> = {",
    ...Object.keys(map).sort().map((id) => `  "${id}": "${map[id]}",`),
    "};",
    "",
    "export const getWineImageById = (id: string): string | null =>",
    "  WINE_IMAGE_MAP[id] ?? null;",
    "",
  ];
  const outPath = path.resolve(process.cwd(), "src", "data", "wine-images.ts");
  await fs.writeFile(outPath, lines.join("\n"), "utf8");
  console.log(`\nWrote ${outPath} (${Object.keys(map).length} entries)`);
}

async function main() {
  const restaurants = ONLY_SLUG
    ? seedRestaurants.filter((r: { slug: string }) => r.slug === ONLY_SLUG)
    : seedRestaurants;
  if (restaurants.length === 0) {
    console.error(`No restaurants matched slug "${ONLY_SLUG}"`);
    process.exit(1);
  }

  let total = 0;
  let ok = 0;
  let failed = 0;
  const map: Record<string, string> = {};

  for (const r of restaurants) {
    console.log(`\n=== ${r.slug} (${r.cuisine}) — ${r.wines.length} wines ===`);
    for (const wine of r.wines) {
      total++;
      const res = await generateOne(
        r.slug,
        wine.id,
        t(wine.name, "en"),
        wine.region,
        wine.grape,
        wine.style,
        t(wine.notes, "en"),
      );
      if (res) {
        ok++;
        map[wine.id] = res.relPath;
      } else {
        failed++;
      }
      await new Promise((res) => setTimeout(res, 400));
    }
  }

  await writeImageMap(map);
  console.log(`\n=== Done ===\n  total : ${total}\n  ok    : ${ok}\n  failed: ${failed}`);
  if (failed > 0) process.exit(2);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
