/**
 * dish-images.ts — generated by scripts/gen-dish-images.mts.
 * Maps every dish id to its public-served photo URL. Consumed by
 * the rendering layer when the dish's seed entry has no `image`.
 * Do NOT hand-edit; re-run the script.
 */

export const DISH_IMAGE_MAP: Record<string, string> = {
  "r1-d1": "/dishes/atelier-amaro/r1-d1.png",
  "r1-d10": "/dishes/atelier-amaro/r1-d10.png",
  "r1-d2": "/dishes/atelier-amaro/r1-d2.png",
  "r1-d3": "/dishes/atelier-amaro/r1-d3.png",
  "r1-d4": "/dishes/atelier-amaro/r1-d4.png",
  "r1-d5": "/dishes/atelier-amaro/r1-d5.png",
  "r1-d6": "/dishes/atelier-amaro/r1-d6.png",
  "r1-d7": "/dishes/atelier-amaro/r1-d7.png",
  "r1-d8": "/dishes/atelier-amaro/r1-d8.png",
  "r1-d9": "/dishes/atelier-amaro/r1-d9.png",
  "r2-d1": "/dishes/senses-warsaw/r2-d1.png",
  "r2-d10": "/dishes/senses-warsaw/r2-d10.png",
  "r2-d2": "/dishes/senses-warsaw/r2-d2.png",
  "r2-d3": "/dishes/senses-warsaw/r2-d3.png",
  "r2-d4": "/dishes/senses-warsaw/r2-d4.png",
  "r2-d5": "/dishes/senses-warsaw/r2-d5.png",
  "r2-d6": "/dishes/senses-warsaw/r2-d6.png",
  "r2-d7": "/dishes/senses-warsaw/r2-d7.png",
  "r2-d8": "/dishes/senses-warsaw/r2-d8.png",
  "r2-d9": "/dishes/senses-warsaw/r2-d9.png",
  "r3-d1": "/dishes/bottiglieria-1881/r3-d1.png",
  "r3-d10": "/dishes/bottiglieria-1881/r3-d10.png",
  "r3-d2": "/dishes/bottiglieria-1881/r3-d2.png",
  "r3-d3": "/dishes/bottiglieria-1881/r3-d3.png",
  "r3-d4": "/dishes/bottiglieria-1881/r3-d4.png",
  "r3-d5": "/dishes/bottiglieria-1881/r3-d5.png",
  "r3-d6": "/dishes/bottiglieria-1881/r3-d6.png",
  "r3-d7": "/dishes/bottiglieria-1881/r3-d7.png",
  "r3-d8": "/dishes/bottiglieria-1881/r3-d8.png",
  "r3-d9": "/dishes/bottiglieria-1881/r3-d9.png",
  "r4-d1": "/dishes/pod-aniolami/r4-d1.png",
  "r4-d10": "/dishes/pod-aniolami/r4-d10.png",
  "r4-d2": "/dishes/pod-aniolami/r4-d2.png",
  "r4-d3": "/dishes/pod-aniolami/r4-d3.png",
  "r4-d4": "/dishes/pod-aniolami/r4-d4.png",
  "r4-d5": "/dishes/pod-aniolami/r4-d5.png",
  "r4-d6": "/dishes/pod-aniolami/r4-d6.png",
  "r4-d7": "/dishes/pod-aniolami/r4-d7.png",
  "r4-d8": "/dishes/pod-aniolami/r4-d8.png",
  "r4-d9": "/dishes/pod-aniolami/r4-d9.png",
  "r5-d1": "/dishes/brovariusz-wroclaw/r5-d1.png",
  "r5-d10": "/dishes/brovariusz-wroclaw/r5-d10.png",
  "r5-d2": "/dishes/brovariusz-wroclaw/r5-d2.png",
  "r5-d3": "/dishes/brovariusz-wroclaw/r5-d3.png",
  "r5-d4": "/dishes/brovariusz-wroclaw/r5-d4.png",
  "r5-d5": "/dishes/brovariusz-wroclaw/r5-d5.png",
  "r5-d6": "/dishes/brovariusz-wroclaw/r5-d6.png",
  "r5-d7": "/dishes/brovariusz-wroclaw/r5-d7.png",
  "r5-d8": "/dishes/brovariusz-wroclaw/r5-d8.png",
  "r5-d9": "/dishes/brovariusz-wroclaw/r5-d9.png",
};

export const getDishImageById = (id: string): string | null =>
  DISH_IMAGE_MAP[id] ?? null;
