/**
 * sense-images.ts - generated by scripts/gen-sense-images.mts.
 * Maps sektor id + tendencja id to their still-life image URL.
 * Do NOT hand-edit; re-run the script.
 */

export const SENSE_IMAGE_MAP: Record<string, string> = {
  "miekkie": "/senses/miekkie.png",
  "miekkie.dojrzale": "/senses/miekkie-dojrzale.png",
  "miekkie.konfitury": "/senses/miekkie-konfitury.png",
  "oleiste": "/senses/oleiste.png",
  "oleiste.maslo": "/senses/oleiste-maslo.png",
  "oleiste.tropikalne": "/senses/oleiste-tropikalne.png",
  "swieze": "/senses/swieze.png",
  "swieze.cytrusy": "/senses/swieze-cytrusy.png",
  "swieze.zielone": "/senses/swieze-zielone.png",
  "szorstkie": "/senses/szorstkie.png",
  "szorstkie.dab": "/senses/szorstkie-dab.png",
  "szorstkie.pizmo": "/senses/szorstkie-pizmo.png",
  "tegie": "/senses/tegie.png",
  "tegie.cigaro": "/senses/tegie-cigaro.png",
  "tegie.suszone": "/senses/tegie-suszone.png",
  "ziemiste": "/senses/ziemiste.png",
  "ziemiste.mineraly": "/senses/ziemiste-mineraly.png",
  "ziemiste.sciolka": "/senses/ziemiste-sciolka.png",
};

export const getSenseImageById = (id: string): string | null =>
  SENSE_IMAGE_MAP[id] ?? null;

/**
 * The CLIENT'S OWN association artwork (vinocompas_graphics/obrazkinut →
 * background-stripped by scratchpad/process-ring.mjs), i.e. the very objects
 * that ring the wheel. Preferred over SENSE_IMAGE_MAP above: those are
 * AI-generated dark still-lifes that read as unreadable murk inside the
 * guide card (client 2026-07-18 "сильно тёмные, нечитабельные"), while these
 * are bright cut-outs on transparency and keep the card visually identical
 * to the garland the guest just clicked.
 *
 * 12 tendencje only — a sektor card composes its two children.
 */
export const RING_IMAGE_MAP: Record<string, string> = {
  "tegie.cigaro": "/senses/ring/tegie-cigaro.png",
  "tegie.suszone": "/senses/ring/tegie-suszone.png",
  "miekkie.dojrzale": "/senses/ring/miekkie-dojrzale.png",
  "miekkie.konfitury": "/senses/ring/miekkie-konfitury.png",
  "oleiste.maslo": "/senses/ring/oleiste-maslo.png",
  "oleiste.tropikalne": "/senses/ring/oleiste-tropikalne.png",
  "swieze.zielone": "/senses/ring/swieze-zielone.png",
  "swieze.cytrusy": "/senses/ring/swieze-cytrusy.png",
  "ziemiste.mineraly": "/senses/ring/ziemiste-mineraly.png",
  "ziemiste.sciolka": "/senses/ring/ziemiste-sciolka.png",
  "szorstkie.pizmo": "/senses/ring/szorstkie-pizmo.png",
  "szorstkie.dab": "/senses/ring/szorstkie-dab.png",
};

/** Images to show for a focused id: one for a tendencja, both children for a
 *  sektor, none for a base taste (the wheel shows no objects for those). */
export function ringImagesFor(id: string): string[] {
  const own = RING_IMAGE_MAP[id];
  if (own) return [own];
  const children = Object.entries(RING_IMAGE_MAP)
    .filter(([k]) => k.startsWith(`${id}.`))
    .map(([, v]) => v);
  return children;
}

/**
 * How many INDIVIDUAL object sprites each tendencja was cut into by
 * scratchpad/slice-ring2.mjs (public/senses/ring/<tendencja>-<k>.png).
 * The whole images above are internally arranged in 2 rows, so rendering one
 * in a wide band reads as a blob huddled mid-card (client 2026-07-18 "не
 * кучку посредине, нужно в полоску") — the card lays these out in a row
 * instead, echoing the wheel's garland.
 */
const RING_SPRITE_COUNTS: Record<string, number> = {
  "tegie.cigaro": 5,
  "tegie.suszone": 5,
  "miekkie.dojrzale": 1,
  "miekkie.konfitury": 3,
  "oleiste.maslo": 1,
  "oleiste.tropikalne": 5,
  "swieze.zielone": 1,
  "swieze.cytrusy": 3,
  "ziemiste.mineraly": 1,
  "ziemiste.sciolka": 5,
  "szorstkie.pizmo": 2,
  "szorstkie.dab": 5,
};

const spritesOf = (tendencjaId: string): string[] => {
  const n = RING_SPRITE_COUNTS[tendencjaId] ?? 0;
  const base = tendencjaId.replace(/\./g, "-");
  return Array.from({ length: n }, (_, i) => `/senses/ring/${base}-${i + 1}.png`);
};

/**
 * Object sprites for a focused id, as a horizontal strip.
 *  - tendencja → its own objects; when it was cut into a single blob, its
 *    SIBLING's objects join the strip so the band never shows one lonely
 *    huddle (both belong to the same sektor, so the pairing still reads true)
 *  - sektor    → objects from both children, evenly taken
 *  - base      → none, matching the wheel
 */
export function ringSpritesFor(id: string, max = 5): string[] {
  if (RING_IMAGE_MAP[id]) {
    const own = spritesOf(id);
    if (own.length >= 3) return own.slice(0, max);
    const sector = id.split(".")[0];
    const sibling = Object.keys(RING_IMAGE_MAP).find(
      (k) => k !== id && k.startsWith(`${sector}.`),
    );
    const extra = sibling ? spritesOf(sibling) : [];
    return [...own, ...extra].slice(0, max);
  }
  const children = Object.keys(RING_IMAGE_MAP).filter((k) => k.startsWith(`${id}.`));
  if (children.length === 0) return [];
  // Interleave so both tendencje of a sektor are represented in the strip.
  const perChild = Math.max(1, Math.ceil(max / children.length));
  return children.flatMap((c) => spritesOf(c).slice(0, perChild)).slice(0, max);
}
