/**
 * sense-images.ts — generated by scripts/gen-sense-images.mts.
 * Maps sektor id + tendencja id to their still-life image URL.
 * Do NOT hand-edit; re-run the script.
 */

export const SENSE_IMAGE_MAP: Record<string, string> = {
  "miekkie": "/senses/miekkie.png",
  "miekkie.dojrzale": "/senses/miekkie-dojrzale.png",
  "miekkie.konfitury": "/senses/miekkie-konfitury.png",
  "oleiste": "/senses/oleiste.png",
  "oleiste.maslo": "/senses/oleiste-maslo.png",
  "oleiste.tropikalne": "/senses/oleiste-tropikalne.png",
  "swieze": "/senses/swieze.png",
  "swieze.cytrusy": "/senses/swieze-cytrusy.png",
  "swieze.zielone": "/senses/swieze-zielone.png",
  "szorstkie": "/senses/szorstkie.png",
  "szorstkie.dab": "/senses/szorstkie-dab.png",
  "szorstkie.pizmo": "/senses/szorstkie-pizmo.png",
  "tegie": "/senses/tegie.png",
  "tegie.cigaro": "/senses/tegie-cigaro.png",
  "tegie.suszone": "/senses/tegie-suszone.png",
  "ziemiste": "/senses/ziemiste.png",
  "ziemiste.mineraly": "/senses/ziemiste-mineraly.png",
  "ziemiste.sciolka": "/senses/ziemiste-sciolka.png",
};

export const getSenseImageById = (id: string): string | null =>
  SENSE_IMAGE_MAP[id] ?? null;
