/**
 * wine-images.ts - generated by scripts/gen-wine-images.mts.
 * Maps every wine id to its public-served bottle photo URL.
 * Do NOT hand-edit; re-run the script.
 */

export const WINE_IMAGE_MAP: Record<string, string> = {
  "r1-w1": "/wines/atelier-amaro/r1-w1.png",
  "r1-w2": "/wines/atelier-amaro/r1-w2.png",
  "r1-w3": "/wines/atelier-amaro/r1-w3.png",
  "r1-w4": "/wines/atelier-amaro/r1-w4.png",
  "r1-w5": "/wines/atelier-amaro/r1-w5.png",
  "r1-w6": "/wines/atelier-amaro/r1-w6.png",
  "r1-w7": "/wines/atelier-amaro/r1-w7.png",
  "r1-w8": "/wines/atelier-amaro/r1-w8.png",
  "r2-w1": "/wines/senses-warsaw/r2-w1.png",
  "r2-w2": "/wines/senses-warsaw/r2-w2.png",
  "r2-w3": "/wines/senses-warsaw/r2-w3.png",
  "r2-w4": "/wines/senses-warsaw/r2-w4.png",
  "r2-w5": "/wines/senses-warsaw/r2-w5.png",
  "r2-w6": "/wines/senses-warsaw/r2-w6.png",
  "r2-w7": "/wines/senses-warsaw/r2-w7.png",
  "r2-w8": "/wines/senses-warsaw/r2-w8.png",
  "r3-w1": "/wines/bottiglieria-1881/r3-w1.png",
  "r3-w2": "/wines/bottiglieria-1881/r3-w2.png",
  "r3-w3": "/wines/bottiglieria-1881/r3-w3.png",
  "r3-w4": "/wines/bottiglieria-1881/r3-w4.png",
  "r3-w5": "/wines/bottiglieria-1881/r3-w5.png",
  "r3-w6": "/wines/bottiglieria-1881/r3-w6.png",
  "r3-w7": "/wines/bottiglieria-1881/r3-w7.png",
  "r3-w8": "/wines/bottiglieria-1881/r3-w8.png",
  "r4-w1": "/wines/pod-aniolami/r4-w1.png",
  "r4-w2": "/wines/pod-aniolami/r4-w2.png",
  "r4-w3": "/wines/pod-aniolami/r4-w3.png",
  "r4-w4": "/wines/pod-aniolami/r4-w4.png",
  "r4-w5": "/wines/pod-aniolami/r4-w5.png",
  "r4-w6": "/wines/pod-aniolami/r4-w6.png",
  "r4-w7": "/wines/pod-aniolami/r4-w7.png",
  "r4-w8": "/wines/pod-aniolami/r4-w8.png",
  "r5-w1": "/wines/brovariusz-wroclaw/r5-w1.png",
  "r5-w2": "/wines/brovariusz-wroclaw/r5-w2.png",
  "r5-w3": "/wines/brovariusz-wroclaw/r5-w3.png",
  "r5-w4": "/wines/brovariusz-wroclaw/r5-w4.png",
  "r5-w5": "/wines/brovariusz-wroclaw/r5-w5.png",
  "r5-w6": "/wines/brovariusz-wroclaw/r5-w6.png",
  "r5-w7": "/wines/brovariusz-wroclaw/r5-w7.png",
  "r5-w8": "/wines/brovariusz-wroclaw/r5-w8.png",
};

export const getWineImageById = (id: string): string | null =>
  WINE_IMAGE_MAP[id] ?? null;
